import Header from "@/components/Header";
import ProductCard from "@/components/ProductCard";
import ProductsList from "@/components/ProductsList";
import { ProductInterface, fetchProducts } from "@/services/products";
import { GetStaticProps } from "next";
import Head from "next/head";
import React, { ReactNode } from "react";
import { Container } from "reactstrap";

export const getStaticProps: GetStaticProps = async () => {
  const products = await fetchProducts();
  return { props: {products}}
}



export default function Products(props: {
  children?: ReactNode,
  products: ProductInterface[]
}) {
  return  (
    <>
      <Head>
        <title>Nossos Produtos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header color="dark" light={true} dark={true} expand="md"/>

      <main>
        <Container className="py-5">
          {props.products && <ProductsList products={props.products}/>}
        </Container>
      </main>
    </>
  );
}
